# Generated by Django 5.2 on 2025-05-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this category as featured on homepage'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this post as featured (will appear in featured section)'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_tutorial_series',
            field=models.BooleanField(default=False, help_text='Is this part of a tutorial series?'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('regular', 'Regular Post'), ('tutorial', 'Tutorial'), ('story', 'Behind the Code Story')], default='regular', help_text='Classification for different post types', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated read time in minutes'),
        ),
        migrations.AddField(
            model_name='post',
            name='tutorial_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in tutorial series (lower numbers come first)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_tutorial_tag',
            field=models.BooleanField(default=False, help_text="Mark this tag as tutorial-related (e.g., 'django', 'python')"),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['featured'], name='blog_post_feature_716fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type'], name='blog_post_post_ty_ffe491_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['tutorial_order'], name='blog_post_tutoria_107767_idx'),
        ),
    ]
